name: Pull request

on:
  pull_request:
    branch: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install
        run: yarn

      - name: Run tests
        run: yarn test

      - name: Typecheck
        run: yarn tsc --noemit

      - name: Lint
        run: yarn eslint . && yarn prettier .
